mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    '*': debug
    com.alibaba.druid.sql: debug
    com.github.spring.security.mapper: debug
    org.springframework.security: debug